name: RDP on Linux (Blacksmith)

on:
  workflow_dispatch:

jobs:
  rdp-setup:
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install XFCE and XRDP
        run: |
          sudo apt update -y
          sudo apt install -y xfce4 xfce4-goodies tightvncserver xrdp
          echo "xfce4-session" > ~/.xsession
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Show Public IP
        run: curl ifconfig.me
